name: CI pipeline

on:
  push:
    branches: [develop, release-* ]
  pull_request:
    branches: [ develop, release-* ]

jobs:
  pipeline:
    if: github.server_url != 'https://github.com'
    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
