name: CI pipeline

on:
  push:
    branches: [develop, release-* ]
  pull_request:
    branches: [ develop, release-* ]

# Cancel in-progress runs exclusively for PR jobs. `github.head_ref` is defined only for PRs,
# for post-merge, it defaults to `github.run_id`, which is guaranteed to be unique.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pipeline:
    if: github.server_url != 'https://github.com'
    uses: ./.github/workflows/pipeline.yml
    secrets: inherit
